name: Security Pipeline Bandit Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bandit-report:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear carpeta de reportes
        run: |
          mkdir -p reports

      - name: Ejecutar Bandit y generar reporte TXT
        run: |
          bandit -r . -x venv -f txt -o reports/reporte_bandit.txt || true

      - name: Mostrar resultado de Bandit en consola
        run: |
          bandit -r . -x venv || true

      - name: Subir reporte como artifact
        uses: actions/upload-artifact@v4
        with:
          name: reporte-bandit-lab08
          path: reports/reporte_bandit.txt